package gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JLabel;
import javax.swing.JPanel;
import other.BienMacDinh;

/**
 *
 * @author vanphatdev
 */
public class GDChinh extends javax.swing.JFrame implements MouseListener{

    private boolean isThuGonMenu = false;
    private int manHinhDangChon = 1;
    /**
     * Creates new form NewJFrame
     */
    public GDChinh() {
        icon();
        this.setTitle("Quản lí khách sạn - VinaHotel");
        initComponents();
        
        customJPanelVaJLableKhiDuocChon(pSoDoPhong, lblSoDoPhong);
        pNDQLDatPhong.setVisible(false);
        pNDQLTraPhong.setVisible(false);
        pNDQLDichVu.setVisible(false);
        pNDQLNhanVien.setVisible(false);
        pNDQLKhachHang.setVisible(false);
        pNDQLHoaDon.setVisible(false);
        
        lblSoDoPhong.addMouseListener(this);
        lblQLDatPhong.addMouseListener(this);
        lblQLTraPhong.addMouseListener(this);
        lblQLDichVu.addMouseListener(this);
        lblQLNhanVien.addMouseListener(this);
        lblQLKhachHang.addMouseListener(this);
        lblQLHoaDon.addMouseListener(this);
    }
    
    public void icon() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/Logo_big.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pBackgroundMain = new javax.swing.JPanel();
        pMenu = new javax.swing.JPanel();
        pLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pSoDoPhong = new javax.swing.JPanel();
        lblSoDoPhong = new javax.swing.JLabel();
        pQLDatPhong = new javax.swing.JPanel();
        lblQLDatPhong = new javax.swing.JLabel();
        pQLTraPhong = new javax.swing.JPanel();
        lblQLTraPhong = new javax.swing.JLabel();
        pQLDichVu = new javax.swing.JPanel();
        lblQLDichVu = new javax.swing.JLabel();
        pQLNhanVien = new javax.swing.JPanel();
        lblQLNhanVien = new javax.swing.JLabel();
        pQLKhachHang = new javax.swing.JPanel();
        lblQLKhachHang = new javax.swing.JLabel();
        pQLHoaDon = new javax.swing.JPanel();
        lblQLHoaDon = new javax.swing.JLabel();
        pDangXuat = new javax.swing.JPanel();
        lblDangXuat = new javax.swing.JLabel();
        pNoiDung = new javax.swing.JPanel();
        pNDSoDoPhong = new javax.swing.JPanel();
        pNDQLDatPhong = new javax.swing.JPanel();
        pNDQLTraPhong = new javax.swing.JPanel();
        pNDQLDichVu = new javax.swing.JPanel();
        pNDQLNhanVien = new javax.swing.JPanel();
        pNDQLKhachHang = new javax.swing.JPanel();
        pNDQLHoaDon = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pMenu.setBackground(new java.awt.Color(183, 219, 243));

        pLogo.setBackground(new java.awt.Color(183, 219, 243));

        lblLogo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(204, 0, 51));
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo_small.jpg"))); // NOI18N
        lblLogo.setText("VinaHotel");
        lblLogo.setIconTextGap(16);
        lblLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pLogoLayout = new javax.swing.GroupLayout(pLogo);
        pLogo.setLayout(pLogoLayout);
        pLogoLayout.setHorizontalGroup(
            pLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pLogoLayout.setVerticalGroup(
            pLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pSoDoPhong.setBackground(new java.awt.Color(183, 219, 243));

        lblSoDoPhong.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lblSoDoPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/houses_32px.png"))); // NOI18N
        lblSoDoPhong.setText("Sơ đồ phòng");
        lblSoDoPhong.setIconTextGap(38);

        javax.swing.GroupLayout pSoDoPhongLayout = new javax.swing.GroupLayout(pSoDoPhong);
        pSoDoPhong.setLayout(pSoDoPhongLayout);
        pSoDoPhongLayout.setHorizontalGroup(
            pSoDoPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSoDoPhongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSoDoPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pSoDoPhongLayout.setVerticalGroup(
            pSoDoPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSoDoPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pQLDatPhong.setBackground(new java.awt.Color(183, 219, 243));

        lblQLDatPhong.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lblQLDatPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/room_service_32px.png"))); // NOI18N
        lblQLDatPhong.setText("Quản lí đặt phòng");
        lblQLDatPhong.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 102)));
        lblQLDatPhong.setIconTextGap(38);

        javax.swing.GroupLayout pQLDatPhongLayout = new javax.swing.GroupLayout(pQLDatPhong);
        pQLDatPhong.setLayout(pQLDatPhongLayout);
        pQLDatPhongLayout.setHorizontalGroup(
            pQLDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pQLDatPhongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLDatPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pQLDatPhongLayout.setVerticalGroup(
            pQLDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQLDatPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pQLTraPhong.setBackground(new java.awt.Color(183, 219, 243));

        lblQLTraPhong.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lblQLTraPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/info_32px.png"))); // NOI18N
        lblQLTraPhong.setText("Quản lí trả phòng");
        lblQLTraPhong.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 102)));
        lblQLTraPhong.setIconTextGap(38);

        javax.swing.GroupLayout pQLTraPhongLayout = new javax.swing.GroupLayout(pQLTraPhong);
        pQLTraPhong.setLayout(pQLTraPhongLayout);
        pQLTraPhongLayout.setHorizontalGroup(
            pQLTraPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pQLTraPhongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLTraPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pQLTraPhongLayout.setVerticalGroup(
            pQLTraPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQLTraPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pQLDichVu.setBackground(new java.awt.Color(183, 219, 243));

        lblQLDichVu.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lblQLDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/water_service_32px.png"))); // NOI18N
        lblQLDichVu.setText("Quản lí dịch vụ");
        lblQLDichVu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 102)));
        lblQLDichVu.setIconTextGap(38);

        javax.swing.GroupLayout pQLDichVuLayout = new javax.swing.GroupLayout(pQLDichVu);
        pQLDichVu.setLayout(pQLDichVuLayout);
        pQLDichVuLayout.setHorizontalGroup(
            pQLDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pQLDichVuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pQLDichVuLayout.setVerticalGroup(
            pQLDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQLDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pQLNhanVien.setBackground(new java.awt.Color(183, 219, 243));

        lblQLNhanVien.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lblQLNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/employee_32px.png"))); // NOI18N
        lblQLNhanVien.setText("Quản lí nhân viên");
        lblQLNhanVien.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 102)));
        lblQLNhanVien.setIconTextGap(38);

        javax.swing.GroupLayout pQLNhanVienLayout = new javax.swing.GroupLayout(pQLNhanVien);
        pQLNhanVien.setLayout(pQLNhanVienLayout);
        pQLNhanVienLayout.setHorizontalGroup(
            pQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pQLNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pQLNhanVienLayout.setVerticalGroup(
            pQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQLNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pQLKhachHang.setBackground(new java.awt.Color(183, 219, 243));

        lblQLKhachHang.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lblQLKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/customer_32px.png"))); // NOI18N
        lblQLKhachHang.setText("Quản lí khách hàng");
        lblQLKhachHang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 102)));
        lblQLKhachHang.setIconTextGap(38);

        javax.swing.GroupLayout pQLKhachHangLayout = new javax.swing.GroupLayout(pQLKhachHang);
        pQLKhachHang.setLayout(pQLKhachHangLayout);
        pQLKhachHangLayout.setHorizontalGroup(
            pQLKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pQLKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pQLKhachHangLayout.setVerticalGroup(
            pQLKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQLKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pQLHoaDon.setBackground(new java.awt.Color(183, 219, 243));

        lblQLHoaDon.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lblQLHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/payment_32px.png"))); // NOI18N
        lblQLHoaDon.setText("Quản lí hoá hơn");
        lblQLHoaDon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 102)));
        lblQLHoaDon.setIconTextGap(38);

        javax.swing.GroupLayout pQLHoaDonLayout = new javax.swing.GroupLayout(pQLHoaDon);
        pQLHoaDon.setLayout(pQLHoaDonLayout);
        pQLHoaDonLayout.setHorizontalGroup(
            pQLHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pQLHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pQLHoaDonLayout.setVerticalGroup(
            pQLHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQLHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pDangXuat.setBackground(new java.awt.Color(183, 219, 243));

        lblDangXuat.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lblDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout_32px.png"))); // NOI18N
        lblDangXuat.setText("Đăng xuất");
        lblDangXuat.setIconTextGap(38);
        lblDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pDangXuatLayout = new javax.swing.GroupLayout(pDangXuat);
        pDangXuat.setLayout(pDangXuatLayout);
        pDangXuatLayout.setHorizontalGroup(
            pDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDangXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pDangXuatLayout.setVerticalGroup(
            pDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pMenuLayout = new javax.swing.GroupLayout(pMenu);
        pMenu.setLayout(pMenuLayout);
        pMenuLayout.setHorizontalGroup(
            pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pSoDoPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pQLDatPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pQLTraPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pQLDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pQLNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pQLKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pQLHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pMenuLayout.setVerticalGroup(
            pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuLayout.createSequentialGroup()
                .addComponent(pLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pSoDoPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pQLDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pQLTraPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pQLDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pQLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pQLKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pQLHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pNoiDung.setLayout(new javax.swing.OverlayLayout(pNoiDung));

        pNDSoDoPhong.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout pNDSoDoPhongLayout = new javax.swing.GroupLayout(pNDSoDoPhong);
        pNDSoDoPhong.setLayout(pNDSoDoPhongLayout);
        pNDSoDoPhongLayout.setHorizontalGroup(
            pNDSoDoPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 962, Short.MAX_VALUE)
        );
        pNDSoDoPhongLayout.setVerticalGroup(
            pNDSoDoPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        pNoiDung.add(pNDSoDoPhong);

        pNDQLDatPhong.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout pNDQLDatPhongLayout = new javax.swing.GroupLayout(pNDQLDatPhong);
        pNDQLDatPhong.setLayout(pNDQLDatPhongLayout);
        pNDQLDatPhongLayout.setHorizontalGroup(
            pNDQLDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 962, Short.MAX_VALUE)
        );
        pNDQLDatPhongLayout.setVerticalGroup(
            pNDQLDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        pNoiDung.add(pNDQLDatPhong);

        pNDQLTraPhong.setBackground(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout pNDQLTraPhongLayout = new javax.swing.GroupLayout(pNDQLTraPhong);
        pNDQLTraPhong.setLayout(pNDQLTraPhongLayout);
        pNDQLTraPhongLayout.setHorizontalGroup(
            pNDQLTraPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 962, Short.MAX_VALUE)
        );
        pNDQLTraPhongLayout.setVerticalGroup(
            pNDQLTraPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        pNoiDung.add(pNDQLTraPhong);

        pNDQLDichVu.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout pNDQLDichVuLayout = new javax.swing.GroupLayout(pNDQLDichVu);
        pNDQLDichVu.setLayout(pNDQLDichVuLayout);
        pNDQLDichVuLayout.setHorizontalGroup(
            pNDQLDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 962, Short.MAX_VALUE)
        );
        pNDQLDichVuLayout.setVerticalGroup(
            pNDQLDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        pNoiDung.add(pNDQLDichVu);

        pNDQLNhanVien.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout pNDQLNhanVienLayout = new javax.swing.GroupLayout(pNDQLNhanVien);
        pNDQLNhanVien.setLayout(pNDQLNhanVienLayout);
        pNDQLNhanVienLayout.setHorizontalGroup(
            pNDQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 962, Short.MAX_VALUE)
        );
        pNDQLNhanVienLayout.setVerticalGroup(
            pNDQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        pNoiDung.add(pNDQLNhanVien);

        pNDQLKhachHang.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout pNDQLKhachHangLayout = new javax.swing.GroupLayout(pNDQLKhachHang);
        pNDQLKhachHang.setLayout(pNDQLKhachHangLayout);
        pNDQLKhachHangLayout.setHorizontalGroup(
            pNDQLKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 962, Short.MAX_VALUE)
        );
        pNDQLKhachHangLayout.setVerticalGroup(
            pNDQLKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        pNoiDung.add(pNDQLKhachHang);

        pNDQLHoaDon.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout pNDQLHoaDonLayout = new javax.swing.GroupLayout(pNDQLHoaDon);
        pNDQLHoaDon.setLayout(pNDQLHoaDonLayout);
        pNDQLHoaDonLayout.setHorizontalGroup(
            pNDQLHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 962, Short.MAX_VALUE)
        );
        pNDQLHoaDonLayout.setVerticalGroup(
            pNDQLHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        pNoiDung.add(pNDQLHoaDon);

        javax.swing.GroupLayout pBackgroundMainLayout = new javax.swing.GroupLayout(pBackgroundMain);
        pBackgroundMain.setLayout(pBackgroundMainLayout);
        pBackgroundMainLayout.setHorizontalGroup(
            pBackgroundMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBackgroundMainLayout.createSequentialGroup()
                .addComponent(pMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pNoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pBackgroundMainLayout.setVerticalGroup(
            pBackgroundMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pNoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pBackgroundMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pBackgroundMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoMouseClicked
        if (isThuGonMenu == false) {
            pMenu.setPreferredSize(new Dimension(76,740));
            pMenu.revalidate();
            pMenu.repaint();
            isThuGonMenu = true;
        } else {
            pMenu.setPreferredSize(new Dimension(230,740));
            pMenu.revalidate();
            pMenu.repaint();
            isThuGonMenu = false;
        }
    }//GEN-LAST:event_lblLogoMouseClicked

    private void lblDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseExited
        pDangXuat.setBackground(BienMacDinh.mauNenMenu);
        lblDangXuat.setForeground(BienMacDinh.mauDen);
    }//GEN-LAST:event_lblDangXuatMouseExited

    private void lblDangXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseEntered
        pDangXuat.setBackground(BienMacDinh.mauDanhMucDangChon);
        lblDangXuat.setForeground(BienMacDinh.mauTrang);
    }//GEN-LAST:event_lblDangXuatMouseEntered

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblQLDatPhong;
    private javax.swing.JLabel lblQLDichVu;
    private javax.swing.JLabel lblQLHoaDon;
    private javax.swing.JLabel lblQLKhachHang;
    private javax.swing.JLabel lblQLNhanVien;
    private javax.swing.JLabel lblQLTraPhong;
    private javax.swing.JLabel lblSoDoPhong;
    private javax.swing.JPanel pBackgroundMain;
    private javax.swing.JPanel pDangXuat;
    private javax.swing.JPanel pLogo;
    private javax.swing.JPanel pMenu;
    private javax.swing.JPanel pNDQLDatPhong;
    private javax.swing.JPanel pNDQLDichVu;
    private javax.swing.JPanel pNDQLHoaDon;
    private javax.swing.JPanel pNDQLKhachHang;
    private javax.swing.JPanel pNDQLNhanVien;
    private javax.swing.JPanel pNDQLTraPhong;
    private javax.swing.JPanel pNDSoDoPhong;
    private javax.swing.JPanel pNoiDung;
    private javax.swing.JPanel pQLDatPhong;
    private javax.swing.JPanel pQLDichVu;
    private javax.swing.JPanel pQLHoaDon;
    private javax.swing.JPanel pQLKhachHang;
    private javax.swing.JPanel pQLNhanVien;
    private javax.swing.JPanel pQLTraPhong;
    private javax.swing.JPanel pSoDoPhong;
    // End of variables declaration//GEN-END:variables

    public void customJPanelVaJLableKhiDuocChon(JPanel p, JLabel lbl) {
        p.setBackground(BienMacDinh.mauDanhMucDangChon);
        lbl.setForeground(BienMacDinh.mauTrang);
        lbl.setBorder(null);
    }
    
    public void customJPanelVaJLableKhiKhongDuocChon(JPanel p, JLabel lbl) {
        p.setBackground(BienMacDinh.mauNenMenu);
        lbl.setForeground(BienMacDinh.mauDen);
        lbl.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, BienMacDinh.mauBorderBottomMenu));
    }
    
    @Override
    public void mouseClicked(MouseEvent e) {
        Object o = e.getSource();
        if (o.equals(lblSoDoPhong)) {
            pNDSoDoPhong.setVisible(true); // Màn hình được chọn
            pNDQLDatPhong.setVisible(false);
            pNDQLTraPhong.setVisible(false);
            pNDQLDichVu.setVisible(false);
            pNDQLNhanVien.setVisible(false);
            pNDQLKhachHang.setVisible(false);
            pNDQLHoaDon.setVisible(false);
            
            customJPanelVaJLableKhiDuocChon(pSoDoPhong, lblSoDoPhong); // Được chọn
            customJPanelVaJLableKhiKhongDuocChon(pQLDatPhong, lblQLDatPhong);
            customJPanelVaJLableKhiKhongDuocChon(pQLTraPhong, lblQLTraPhong);
            customJPanelVaJLableKhiKhongDuocChon(pQLDichVu, lblQLDichVu);
            customJPanelVaJLableKhiKhongDuocChon(pQLNhanVien, lblQLNhanVien);
            customJPanelVaJLableKhiKhongDuocChon(pQLKhachHang, lblQLKhachHang);
            customJPanelVaJLableKhiKhongDuocChon(pQLHoaDon, lblQLHoaDon);
            
            manHinhDangChon = 1;
            
        } else if (o.equals(lblQLDatPhong)) {
            pNDSoDoPhong.setVisible(false);
            pNDQLDatPhong.setVisible(true); // Màn hình được chọn
            pNDQLTraPhong.setVisible(false);
            pNDQLDichVu.setVisible(false);
            pNDQLNhanVien.setVisible(false);
            pNDQLKhachHang.setVisible(false);
            pNDQLHoaDon.setVisible(false);
            
            customJPanelVaJLableKhiKhongDuocChon(pSoDoPhong, lblSoDoPhong); 
            customJPanelVaJLableKhiDuocChon(pQLDatPhong, lblQLDatPhong); // Được chọn
            customJPanelVaJLableKhiKhongDuocChon(pQLTraPhong, lblQLTraPhong);
            customJPanelVaJLableKhiKhongDuocChon(pQLDichVu, lblQLDichVu);
            customJPanelVaJLableKhiKhongDuocChon(pQLNhanVien, lblQLNhanVien);
            customJPanelVaJLableKhiKhongDuocChon(pQLKhachHang, lblQLKhachHang);
            customJPanelVaJLableKhiKhongDuocChon(pQLHoaDon, lblQLHoaDon);
            
            manHinhDangChon = 2;
            
        } else if (o.equals(lblQLTraPhong)) {
            pNDSoDoPhong.setVisible(false); 
            pNDQLDatPhong.setVisible(false);
            pNDQLTraPhong.setVisible(true); // Màn hình được chọn
            pNDQLDichVu.setVisible(false);
            pNDQLNhanVien.setVisible(false);
            pNDQLKhachHang.setVisible(false);
            pNDQLHoaDon.setVisible(false);
            
            customJPanelVaJLableKhiKhongDuocChon(pSoDoPhong, lblSoDoPhong); 
            customJPanelVaJLableKhiKhongDuocChon(pQLDatPhong, lblQLDatPhong);
            customJPanelVaJLableKhiDuocChon(pQLTraPhong, lblQLTraPhong); // Được chọn
            customJPanelVaJLableKhiKhongDuocChon(pQLDichVu, lblQLDichVu);
            customJPanelVaJLableKhiKhongDuocChon(pQLNhanVien, lblQLNhanVien);
            customJPanelVaJLableKhiKhongDuocChon(pQLKhachHang, lblQLKhachHang);
            customJPanelVaJLableKhiKhongDuocChon(pQLHoaDon, lblQLHoaDon);;
            
            manHinhDangChon = 3;
            
        } else if (o.equals(lblQLDichVu)) {
            pNDSoDoPhong.setVisible(false); 
            pNDQLDatPhong.setVisible(false);
            pNDQLTraPhong.setVisible(false); 
            pNDQLDichVu.setVisible(true); // Màn hình được chọn
            pNDQLNhanVien.setVisible(false);
            pNDQLKhachHang.setVisible(false);
            pNDQLHoaDon.setVisible(false);
            
            customJPanelVaJLableKhiKhongDuocChon(pSoDoPhong, lblSoDoPhong); 
            customJPanelVaJLableKhiKhongDuocChon(pQLDatPhong, lblQLDatPhong);
            customJPanelVaJLableKhiKhongDuocChon(pQLTraPhong, lblQLTraPhong); 
            customJPanelVaJLableKhiDuocChon(pQLDichVu, lblQLDichVu); // Được chọn
            customJPanelVaJLableKhiKhongDuocChon(pQLNhanVien, lblQLNhanVien);            
            customJPanelVaJLableKhiKhongDuocChon(pQLKhachHang, lblQLKhachHang);
            customJPanelVaJLableKhiKhongDuocChon(pQLHoaDon, lblQLHoaDon);
            
            manHinhDangChon = 4;
            
        } else if (o.equals(lblQLNhanVien)) {
            pNDSoDoPhong.setVisible(false); 
            pNDQLDatPhong.setVisible(false);
            pNDQLTraPhong.setVisible(false); 
            pNDQLDichVu.setVisible(false); 
            pNDQLNhanVien.setVisible(true); // Màn hình được chọn
            pNDQLKhachHang.setVisible(false);
            pNDQLHoaDon.setVisible(false);
            
            customJPanelVaJLableKhiKhongDuocChon(pSoDoPhong, lblSoDoPhong); 
            customJPanelVaJLableKhiKhongDuocChon(pQLDatPhong, lblQLDatPhong);
            customJPanelVaJLableKhiKhongDuocChon(pQLTraPhong, lblQLTraPhong); 
            customJPanelVaJLableKhiKhongDuocChon(pQLDichVu, lblQLDichVu);
            customJPanelVaJLableKhiDuocChon(pQLNhanVien, lblQLNhanVien);  // Được chọn
            customJPanelVaJLableKhiKhongDuocChon(pQLKhachHang, lblQLKhachHang);
            customJPanelVaJLableKhiKhongDuocChon(pQLHoaDon, lblQLHoaDon);
            
            manHinhDangChon = 5;
            
        } else if (o.equals(lblQLKhachHang)) {
            pNDSoDoPhong.setVisible(false); 
            pNDQLDatPhong.setVisible(false);
            pNDQLTraPhong.setVisible(false); 
            pNDQLDichVu.setVisible(false); 
            pNDQLNhanVien.setVisible(false);
            pNDQLKhachHang.setVisible(true); // Màn hình được chọn
            pNDQLHoaDon.setVisible(false);
            
            customJPanelVaJLableKhiKhongDuocChon(pSoDoPhong, lblSoDoPhong); 
            customJPanelVaJLableKhiKhongDuocChon(pQLDatPhong, lblQLDatPhong);
            customJPanelVaJLableKhiKhongDuocChon(pQLTraPhong, lblQLTraPhong); 
            customJPanelVaJLableKhiKhongDuocChon(pQLDichVu, lblQLDichVu);
            customJPanelVaJLableKhiKhongDuocChon(pQLNhanVien, lblQLNhanVien);  
            customJPanelVaJLableKhiDuocChon(pQLKhachHang, lblQLKhachHang); // Được chọn
            customJPanelVaJLableKhiKhongDuocChon(pQLHoaDon, lblQLHoaDon);
            
            manHinhDangChon = 6;
            
        } else if (o.equals(lblQLHoaDon)) {
            pNDSoDoPhong.setVisible(false); 
            pNDQLDatPhong.setVisible(false);
            pNDQLTraPhong.setVisible(false); 
            pNDQLDichVu.setVisible(false); 
            pNDQLNhanVien.setVisible(false);
            pNDQLKhachHang.setVisible(false); 
            pNDQLHoaDon.setVisible(true); // Màn hình được chọn
            
            customJPanelVaJLableKhiKhongDuocChon(pSoDoPhong, lblSoDoPhong); 
            customJPanelVaJLableKhiKhongDuocChon(pQLDatPhong, lblQLDatPhong);
            customJPanelVaJLableKhiKhongDuocChon(pQLTraPhong, lblQLTraPhong); 
            customJPanelVaJLableKhiKhongDuocChon(pQLDichVu, lblQLDichVu);
            customJPanelVaJLableKhiKhongDuocChon(pQLNhanVien, lblQLNhanVien);  
            customJPanelVaJLableKhiKhongDuocChon(pQLKhachHang, lblQLKhachHang); 
            customJPanelVaJLableKhiDuocChon(pQLHoaDon, lblQLHoaDon); // Được chọn
            
            manHinhDangChon = 7;
            
        }
    }

    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        Object o = e.getSource();
        if (o.equals(lblSoDoPhong)) {
            customJPanelVaJLableKhiDuocChon(pSoDoPhong, lblSoDoPhong);
        }
        if (o.equals(lblQLDatPhong)) {
            customJPanelVaJLableKhiDuocChon(pQLDatPhong, lblQLDatPhong);
        }
        if (o.equals(lblQLTraPhong)) {
            customJPanelVaJLableKhiDuocChon(pQLTraPhong, lblQLTraPhong);
        }
        if (o.equals(lblQLDichVu)) {
            customJPanelVaJLableKhiDuocChon(pQLDichVu, lblQLDichVu);
        }
        if (o.equals(lblQLNhanVien)) {
            customJPanelVaJLableKhiDuocChon(pQLNhanVien, lblQLNhanVien);
        }
        if (o.equals(lblQLKhachHang)) {
            customJPanelVaJLableKhiDuocChon(pQLKhachHang, lblQLKhachHang);
        }
        if (o.equals(lblQLHoaDon)) {
            customJPanelVaJLableKhiDuocChon(pQLHoaDon, lblQLHoaDon);
        }
    }

    @Override
    public void mouseExited(MouseEvent e) {
        Object o = e.getSource();
        if (o.equals(lblSoDoPhong) && manHinhDangChon != 1) {
            customJPanelVaJLableKhiKhongDuocChon(pSoDoPhong, lblSoDoPhong);
        }
        if (o.equals(lblQLDatPhong) && manHinhDangChon != 2) {
            customJPanelVaJLableKhiKhongDuocChon(pQLDatPhong, lblQLDatPhong);
        }
        if (o.equals(lblQLTraPhong) && manHinhDangChon != 3) {
            customJPanelVaJLableKhiKhongDuocChon(pQLTraPhong, lblQLTraPhong);
        }
        if (o.equals(lblQLDichVu) && manHinhDangChon != 4) {
            customJPanelVaJLableKhiKhongDuocChon(pQLDichVu, lblQLDichVu);
        }
        if (o.equals(lblQLNhanVien) && manHinhDangChon != 5) {
            customJPanelVaJLableKhiKhongDuocChon(pQLNhanVien, lblQLNhanVien);
        }
        if (o.equals(lblQLKhachHang) && manHinhDangChon != 6) {
            customJPanelVaJLableKhiKhongDuocChon(pQLKhachHang, lblQLKhachHang);
        }
        if (o.equals(lblQLHoaDon) && manHinhDangChon != 7) {
            customJPanelVaJLableKhiKhongDuocChon(pQLHoaDon, lblQLHoaDon);
        }
    }
}
