
package component;

import entity.Phong;
import entity.LoaiPhong;
import java.awt.Dimension;
import java.awt.event.MouseEvent;
import other.BienMacDinh;

/**
 *
 * @author vanphatdev
 */
public class PanelItemPhong extends javax.swing.JPanel {

    public Phong phong;
    public String maPhong, loaiPhong, trangThaiPhong;
    /**
     * Creates new form PanelItemPhong
     */
    public PanelItemPhong(Phong phong) {
        initComponents();
        this.phong = phong;
        LoaiPhong loaiPhong = phong.getLoaiPhong();
        this.setPreferredSize(new Dimension(238,100));
        
        lblMaPhong.setText(phong.getMaPhong());
        lblLoaiPhong.setText(loaiPhong.getTenLoaiPhong());
        lblTrangThaiPhong.setText(bienDoiTrangThaiPhong(phong.getTrangThaiPhong()));
    }
    
    public PanelItemPhong(String maPhong, String loaiPhong, String trangThaiPhong) {
        initComponents();
        this.setPreferredSize(new Dimension(238,100));
        
        this.maPhong = maPhong;
        this.loaiPhong = loaiPhong;
        this.trangThaiPhong = trangThaiPhong;
        
        lblMaPhong.setText(maPhong);
        lblLoaiPhong.setText(loaiPhong);
        lblTrangThaiPhong.setText(bienDoiTrangThaiPhong(trangThaiPhong));
    }
    
    public String bienDoiTrangThaiPhong(String bdTrangThai) {
        if (bdTrangThai.equals("pt")) {
            pMaPhong.setBackground(BienMacDinh.mauPhongTrong);
            pLoaiThaiPhong.setBackground(BienMacDinh.mauPhongTrongNhat);
            lblLoaiPhong.setForeground(BienMacDinh.mauPhongTrong);
            lblTrangThaiPhong.setForeground(BienMacDinh.mauPhongTrong);
            return "Trống";
        }
        
        if (bdTrangThai.equals("pcn")) {
            pMaPhong.setBackground(BienMacDinh.mauPhongCoNguoi);
            pLoaiThaiPhong.setBackground(BienMacDinh.mauPhongCoNguoiNhat);
            lblLoaiPhong.setForeground(BienMacDinh.mauPhongCoNguoi);
            lblTrangThaiPhong.setForeground(BienMacDinh.mauPhongCoNguoi);
            return "Có người";
        }
        
        if (bdTrangThai.equals("pdt")) {
            pMaPhong.setBackground(BienMacDinh.mauPhongDatTruoc);
            pLoaiThaiPhong.setBackground(BienMacDinh.mauPhongDatTruocNhat);
            lblLoaiPhong.setForeground(BienMacDinh.mauPhongDatTruoc);
            lblTrangThaiPhong.setForeground(BienMacDinh.mauPhongDatTruoc);
            return "Đặt trước";
        }
        
        if (bdTrangThai.equals("pds")) {
            pMaPhong.setBackground(BienMacDinh.mauPhongDangSua);
            pLoaiThaiPhong.setBackground(BienMacDinh.mauPhongDangSuaNhat);
            lblLoaiPhong.setForeground(BienMacDinh.mauPhongDangSua);
            lblTrangThaiPhong.setForeground(BienMacDinh.mauPhongDangSua);
            return "Đang sửa";
        }
        
        return bdTrangThai = "Ngoại lệ!";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pMenuPhong = new javax.swing.JPopupMenu();
        menuDatPhong = new javax.swing.JMenuItem();
        menuNhanPhong = new javax.swing.JMenuItem();
        pMaPhong = new javax.swing.JPanel();
        lblMaPhong = new javax.swing.JLabel();
        pLoaiThaiPhong = new javax.swing.JPanel();
        lblLoaiPhong = new javax.swing.JLabel();
        lblTrangThaiPhong = new javax.swing.JLabel();

        pMenuPhong.setBackground(new java.awt.Color(255, 255, 255));

        menuDatPhong.setBackground(new java.awt.Color(255, 255, 255));
        menuDatPhong.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        menuDatPhong.setText("Đặt phòng");
        menuDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDatPhongActionPerformed(evt);
            }
        });
        pMenuPhong.add(menuDatPhong);

        menuNhanPhong.setBackground(new java.awt.Color(255, 255, 255));
        menuNhanPhong.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        menuNhanPhong.setText("Nhận phòng");
        pMenuPhong.add(menuNhanPhong);

        setBackground(new java.awt.Color(228, 230, 233));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        pMaPhong.setBackground(new java.awt.Color(4, 135, 217));

        lblMaPhong.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        lblMaPhong.setForeground(new java.awt.Color(255, 255, 255));
        lblMaPhong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaPhong.setText("P001");

        javax.swing.GroupLayout pMaPhongLayout = new javax.swing.GroupLayout(pMaPhong);
        pMaPhong.setLayout(pMaPhongLayout);
        pMaPhongLayout.setHorizontalGroup(
            pMaPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pMaPhongLayout.setVerticalGroup(
            pMaPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMaPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblLoaiPhong.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        lblLoaiPhong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoaiPhong.setText("LoaiPhong");

        lblTrangThaiPhong.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        lblTrangThaiPhong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTrangThaiPhong.setText("TrinhTrang");

        javax.swing.GroupLayout pLoaiThaiPhongLayout = new javax.swing.GroupLayout(pLoaiThaiPhong);
        pLoaiThaiPhong.setLayout(pLoaiThaiPhongLayout);
        pLoaiThaiPhongLayout.setHorizontalGroup(
            pLoaiThaiPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLoaiPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTrangThaiPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
        );
        pLoaiThaiPhongLayout.setVerticalGroup(
            pLoaiThaiPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoaiThaiPhongLayout.createSequentialGroup()
                .addComponent(lblLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTrangThaiPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pLoaiThaiPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(pMaPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pLoaiThaiPhong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            System.out.println("Ban da an vao phong: " + maPhong);
            pMenuPhong.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_formMouseClicked

    private void menuDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDatPhongActionPerformed
        System.out.println("dat phong menu: " + maPhong);
    }//GEN-LAST:event_menuDatPhongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLoaiPhong;
    private javax.swing.JLabel lblMaPhong;
    private javax.swing.JLabel lblTrangThaiPhong;
    private javax.swing.JMenuItem menuDatPhong;
    private javax.swing.JMenuItem menuNhanPhong;
    private javax.swing.JPanel pLoaiThaiPhong;
    private javax.swing.JPanel pMaPhong;
    private javax.swing.JPopupMenu pMenuPhong;
    // End of variables declaration//GEN-END:variables
}
